<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "A-level (GCE Advanced level) – это программа выпускных классов средней школы в Великобритании. Диплом A-level дает возможность поступать в любой университет Великобритании, а также признается многими университетами других стран.");
$APPLICATION->SetTitle("A-level");
?><h1 class="text-center">ПРОГРАММА A-LEVEL</h1>

<span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">A-level (GCE Advanced level)&nbsp;– это традиционная программа выпускных классов средней школы в Великобритании, изучаемая на 12-м и 13-м годах&nbsp;обучения.</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">Диплом A-level является своего рода альтернативой российскому школьному аттестату о среднем образовании, но в отличие от последнего дает школьнику возможность поступать в любой университет Великобритании, а также признается лучшими университетами других стран. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">Программа A-level является аналогом международной программы&nbsp;International&nbsp;Baccalaureate. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Содержание программы A-level<img width="512" alt="Программа A-level в Великобритании" src="/upload/medialibrary/67c/students-quad.jpg" height="341" title="Программа A-level в Великобритании" align="right"></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></b></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
В отличие от большинства европейских программ старшей школы, на программе A-level учащиеся углубленно изучают только 3 обязательных предмета, по которым затем сдают выпускные экзамены, результаты которых влияют на возможность поступления на бакалавриат. Выбор предметов очень важен: до перехода в 12 класс школьнику необходимо определиться с будущей специальностью, уточнить требования приоритетного университета, а также проверить, какие комбинации предметов необходимы для поступления на выбранную им специальность. Так, например, для студентов, заинтересованных в изучении Компьютерных технологий, рекомендованными предметами на уровне A-level будут Математика, Физика и Информатика. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Помимо стандартных предметов, учебный план предполагает занятия спортом, творчеством, углубленную подготовку по английскому языку для иностранных студентов, индивидуальные занятия для успешной сдачи дополнительных экзаменов SAT, IELTS, TOEFL, UCAT, BMAT и других. Также&nbsp;для студентов, нацеленных на поступление в максимально рейтинговые университеты, предлагается участие в специализированном курсе Extended Project Qualification, дающем дополнительные баллы при подаче заявок. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Продолжительность программы A-level</span></b><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Стандартная программа обучения длится 2 года. Тем не менее, ряд учебных центров для студентов с выдающимися академическими способностями и свободным английским предлагает возможность получить британский аттестат по окончании интенсивной одногодичной программы. Также&nbsp;для школьников, чей уровень английского языка и оценок недостаточно высок для зачисления на стандартный курс, может быть предложено обучение на расширенной программе A-level, длительностью до 8 триместров. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Где можно пройти программу&nbsp;A-level</span></b><span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Курс A-level можно пройти как в&nbsp;</span><a href="https://www.iclass.ru/secondary-education/great-britain/#schools"><span style="font-family: Arial, Helvetica; font-size: 11pt;">британской школе</span></a><span style="font-family: Arial, Helvetica; font-size: 11pt;">, так и в&nbsp;</span><a href="https://www.iclass.ru/secondary-education/great-britain/#schools"><span style="font-family: Arial, Helvetica; font-size: 11pt;">колледже</span></a><span style="font-family: Arial, Helvetica; font-size: 11pt;">&nbsp;или в </span><a href="https://www.iclass.ru/higher-education/great-britain/preparation-centre/into-university-partnerships/"><span style="font-family: Arial, Helvetica; font-size: 11pt;">подготовительном центре</span></a><span style="font-family: Arial, Helvetica; font-size: 11pt;">.&nbsp;</span></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">Выбор учебного заведения для прохождения данной программы является очень важным и ответственным шагом, ведь у каждого варианта есть свои неоспоримые преимущества.</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;">
Обучение на курсе A-level на базе школы-пансиона является традиционным и наиболее распространенным среди иностранных студентов вариантом: ребенок проживает и обучается на одной территории, где расположены и учебные&nbsp;классы, и&nbsp;комфортные&nbsp;общежития, а также спортивные залы, бассейн, библиотеки, столовая, зоны отдыха,&nbsp;медицинский пункт - в общем все необходимое школьнику для жизни и учебы. Часто такие школы расположены в сельской местности, что положительно сказывается на общей атмосфере учебного заведения, где ничего не отвлекает от процесса учебы, а также гарантирует полную безопасность и защищенность всем ученикам. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">Обучение по программе A-level на базе международного колледжа подходит более самостоятельным ребятам, которые предпочитают активную жизнь больших городов и привыкли к интенсивной учебе. Такие колледжи расположены в Лондоне, Бирмингеме, Манчестере и часто находятся в самом&nbsp;центре города, в небольшом отдалении от студенческих резиденций, до которых студенты добираются на общественном транспорте или пешком. При этом учебные классы в международных колледжах обычно совсем небольшие, что позволяет максимально глубоко усвоить материал и сдать экзамены на самый высокий балл. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Вступительные требования для российских студентов</span></b></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span>
<ul>
	<li><span style="font-family: Arial, Helvetica; font-size: 11pt;">Достижение 16-летнего возраста </span></li>
	<li><span style="font-family: Arial, Helvetica; font-size: 11pt;">Документ об образовании (аттестат/диплом) </span></li>
	<li><span style="font-family: Arial, Helvetica; font-size: 11pt;">Характеристика из школы </span></li>
	<li><span style="font-family: Arial, Helvetica; font-size: 11pt;">Успешная сдача вступительных&nbsp;тестов&nbsp;по английскому языку, математике и иным выбранным предметам</span></li>
</ul>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Преимущества программы A-level</span></b><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Получение диплома A-level с хорошими оценками является гарантией поступления в рейтинговый британский университет на перспективную специальность, включая такие востребованные направления как Медицина, Ветеринария, Архитектура, Биоинженерия или Театральное мастерство. Обучение по традиционной британской системе в старшей школе – залог успешного обучения на уровне бакалавриата в любом вузе мира. А возможность сконцентрироваться только на важных и нужных предметах на последних годах обучения дает ученикам шанс показать наиболее высокие результаты в интересующих их областях знаний и добиться выдающихся показателей на выбранном профессиональном пути. </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><b><span style="font-family: Arial, Helvetica; font-size: 11pt;">Почему стоит обратиться в Ай Класс при поступлении в школу за рубежом?</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></b></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;">
Специалисты Образовательного центра Ай Класс помогут вам разобраться во всех вопросах, связанных с обучением в старшей школе в Великобритании на программе A-level, а также выбрать оптимальную школу или колледж с учетом ваших академических и языковых исходных данных, интересов и планов, финансовых и временных возможностей, помогут избежать ошибок, которые могут стоить вам не только финансов, но и времени.</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;">
На бесплатной консультации мы расскажем вам о системе образования в разных странах, о том, как выбрать университет и программу, на что обратить особое внимание и поможем составить ваш личный план подготовки и поступления.</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 12pt;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Запишитесь на консультацию&nbsp;</span><a href="https://iclass-news.ru/consultation"><span style="font-family: Arial, Helvetica; font-size: 11pt;">по ссылке</span></a><span style="font-family: Arial, Helvetica; font-size: 11pt;">,&nbsp;оставьте ваш вопрос в форме на странице ниже или позвоните нам по телефону (812) 2449964.</span></span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times;"><span style="font-family: Arial, Helvetica; font-size: 11pt;">
Консультации могут проходить как очно, так и онлайн по Zoom.</span><br>
 <span style="font-family: Arial, Helvetica; font-size: 11pt;"> </span></span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times;"><br>
 </span>
<p>
</p>
<p>
</p><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>