<?
    require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("title", "События | Образовательный центр «Ай Класс»");
    $APPLICATION->SetPageProperty("description",
        "Различные события: выставки, олимпиады и конкурсы, семинары и презентации");
    $APPLICATION->SetTitle("События");
?><!--<h1 class="text-center">События</h1>
<div class="link_list"><span><a href="#">семинары</a><a href="#">выставки</a><a href="#">дни открытых дверей</a></span></div>
<h2>мероприятия в январе</h2>-->
<? $APPLICATION->IncludeComponent(
    "bitrix:news",
    "events",
    array(
        "IBLOCK_TYPE"                     => "events",
        "IBLOCK_ID"                       => "8",
        "NEWS_COUNT"                      => "20",
        "SORT_BY1"                        => "ACTIVE_FROM",
        "SORT_ORDER1"                     => "DESC",
        "SORT_BY2"                        => "ACTIVE_FROM",
        "SORT_ORDER2"                     => "DESC",
        "FILTER_NAME"                     => "",
        "FIELD_CODE"                      => array(
            0 => "DETAIL_TEXT",
            1 => "DATE_ACTIVE_FROM",
            2 => "DATE_ACTIVE_TO",
            3 => "",
        ),
        "PROPERTY_CODE"                   => array(
            0 => "",
            1 => "",
        ),
        "CHECK_DATES"                     => "N",
        "DETAIL_URL"                      => "",
        "AJAX_MODE"                       => "N",
        "AJAX_OPTION_JUMP"                => "N",
        "AJAX_OPTION_STYLE"               => "N",
        "AJAX_OPTION_HISTORY"             => "N",
        "CACHE_TYPE"                      => "A",
        "CACHE_TIME"                      => "36000000",
        "CACHE_FILTER"                    => "N",
        "CACHE_GROUPS"                    => "Y",
        "PREVIEW_TRUNCATE_LEN"            => "",
        "ACTIVE_DATE_FORMAT"              => "d-m-Y",
        "SET_STATUS_404"                  => "Y",
        "SHOW_404"                        => "Y",
        "SET_TITLE"                       => "Y",
        "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
        "ADD_SECTIONS_CHAIN"              => "Y",
        "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
        "PARENT_SECTION"                  => "",
        "PARENT_SECTION_CODE"             => "",
        "INCLUDE_SUBSECTIONS"             => "Y",
        "PAGER_TEMPLATE"                  => ".default",
        "DISPLAY_TOP_PAGER"               => "N",
        "DISPLAY_BOTTOM_PAGER"            => "N",
        "PAGER_TITLE"                     => "Новости",
        "PAGER_SHOW_ALWAYS"               => "N",
        "PAGER_DESC_NUMBERING"            => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL"                  => "N",
        "AJAX_OPTION_ADDITIONAL"          => "",
        "CAN_REGISTER"                    => "Y",
        "USE_SEARCH"                      => "N",
        "USE_RSS"                         => "N",
        "USE_RATING"                      => "N",
        "USE_CATEGORIES"                  => "N",
        "USE_FILTER"                      => "N",
        "SEF_MODE"                        => "Y",
        "SEF_FOLDER"                      => "/events/",
        "ADD_ELEMENT_CHAIN"               => "N",
        "USE_PERMISSIONS"                 => "N",
        "LIST_ACTIVE_DATE_FORMAT"         => "d.m.Y",
        "LIST_FIELD_CODE"                 => array(
            0 => "DETAIL_TEXT",
            1 => "DATE_ACTIVE_FROM",
            2 => "DATE_ACTIVE_TO",
            3 => "",
        ),
        "LIST_PROPERTY_CODE"              => array(
            0 => "REGISTER_ALLOW",
            1 => "",
        ),
        "DISPLAY_NAME"                    => "Y",
        "META_KEYWORDS"                   => "-",
        "META_DESCRIPTION"                => "-",
        "BROWSER_TITLE"                   => "-",
        "DETAIL_ACTIVE_DATE_FORMAT"       => "d.m.Y",
        "DETAIL_FIELD_CODE"               => array(
            0 => "DETAIL_TEXT",
            1 => "DATE_ACTIVE_FROM",
            2 => "DATE_ACTIVE_TO",
            3 => "",
        ),
        "DETAIL_PROPERTY_CODE"            => array(
            0 => "REGISTER_ALLOW",
            1 => "",
        ),
        "DETAIL_DISPLAY_TOP_PAGER"        => "N",
        "DETAIL_DISPLAY_BOTTOM_PAGER"     => "Y",
        "DETAIL_PAGER_TITLE"              => "Страница",
        "DETAIL_PAGER_TEMPLATE"           => "",
        "DETAIL_PAGER_SHOW_ALL"           => "Y",
        "DISPLAY_DATE"                    => "Y",
        "DISPLAY_PICTURE"                 => "Y",
        "DISPLAY_PREVIEW_TEXT"            => "Y",
        "USE_SHARE"                       => "N",
        "SEF_URL_TEMPLATES"               => array(
            "news"    => "",
            "section" => "#SECTION_CODE#/",
            "detail"  => "#SECTION_CODE#/#ELEMENT_ID#/",
        )
    ),
    false
); ?>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>